### ISSUE TITLE
Seems like the views are not being recycled when component is not in the hierarchy anymore

### ISSUE THREAD

**Issue by zats** [TheodoliteGroup/Theodolite#27]
Here's a little snippet of code, essentially I'm starting a network fetch and replacing component with another once we load the the data

```
  override func render() -> [Component] {
    let component: Component
    let options = LabelComponent.Options(view: ViewOptions(backgroundColor: .red))
    switch self.state ?? State.idle {
    case .loading:
      component = LabelComponent(("Loading", options))
    case let .succeeded(profile):
// the bug is here
      component = LabelComponent((profile.id, LabelComponent.Options()))
    }
    return [
      FlexboxComponent((
        options: FlexOptions(flexDirection: .column),
        children: [FlexChild(component)]
      ))
    ]
  }

  private func startFetchingProfile() {
    self.updateState(state: .loading)
    self.props.fetchProfile { (result) in
        self.updateState(state: .succeeded(profile))
    }
  }
```

<img width="554" alt="screen shot 2018-02-03 at 7 17 30 pm" src="https://user-images.githubusercontent.com/2688806/35773141-67b35ea4-0917-11e8-83a3-51757f3d7384.png">

# Workaround

Not leaving component background color empty issue is resolved. It doesn't just cover previous view but actually reuses it (or at least it seems so)

```
    case let .succeeded(profile):
// the bug is here
      component = LabelComponent((profile.id, LabelComponent.Options(view: ViewOptions(backgroundColor: .blue))))
```

<img width="623" alt="screen shot 2018-02-03 at 7 21 03 pm" src="https://user-images.githubusercontent.com/2688806/35773143-6ffeb22a-0917-11e8-9f2a-02985fd5de94.png">

Is it possible that it has to do with view reuse?

**Comment by ocrickard** [comment]
Huh, that's super weird. Thanks for filing! Will try and debug tomorrow.

**Comment by ocrickard** [comment]
Oh wait, just so I understand, the bug here is that the other view isn't hidden, right?

Otherwise if the question is why the re-render doesn't re-use the view, this is expected behavior, I believe CK would likely behave this way as well. Check out the note I wrote on the view reuse algorithm, and its discussion of persistent attribute shapes.

**Comment by zats** [comment]
Yeah sorry for not being clear, essentially the bug is that the view corresponding to the component that no longer is being displayed isn’t being removed / hidden.

**Comment by ocrickard** [comment]
OK, cool, then I have to debug this. Thanks for clarifying.

**Comment by ocrickard** [comment]
Sorry for the very long delay in fixing this, but I believe this is now resolved.
