### ISSUE TITLE
Making components working with optionals

### ISSUE THREAD

**Issue by zats** [TheodoliteGroup/Theodolite#28]
ComponentKit follows a pattern of "`nil` in, `nil` out"
* For example passing nil text into the label component returns a `nil` instead of `LabelComponent`
* Same way you can pass a `nil` as one of the children into the `FlexboxComponent` and just get it skipped.

I'm not entirely convinced this is a super Swift-y way of dealing, but at the same it makes processing optional data harder:

```
struct Profile {
  let name: String
  let bio: String
  let avatarUrl: URL?
}

// ...

return FlexboxComponent((
  options: props.flexOptions,
  children: [
    FlexChild(component: ProfilePictureComponent((profile.avatarUrl))),
    FlexChild(component: LableComponent((profile.name))),
    FlexChild(component: LableComponent((profile.bio))),
  ])
```

I don't really know what's the right answer here - wanted to start a discussion

**Comment by ocrickard** [comment]
Oh, interesting! I'd like to keep the constructors as simple as possible, but I can see that the alternative approach would involve some really annoying unwrapping. I don't have a great suggestion here just yet.

**Comment by zats** [comment]
Yeah maybe the best approach would be to have more “real life” usages - that would help to make more informed decision
